version: '3.3'
services:
  loadbalancer:
    image: nginx:latest
    ports:
     - 8088:8088
    volumes:
     - ./conf/nginx.conf:/etc/nginx/nginx.conf
     - ./conf.d:/etc/nginx/conf.d
     - ./log:/var/log/nginx
     - ./www:/data/www
     - ../DEVELOP_KEYs-RGU120:/mnt/DEVELOP_KEYs
    networks:
     - net-ui
    logging:
      driver: json-file
#    deploy:
#      placement:
#        constraints:
#         - node.labels.crashed!=true
networks:
  net-ui:
#    driver: overlay
